# Generated by Django 5.1.3 on 2024-11-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentrosincronico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='encuentrosincronico',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='encuentrosincronico',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='encuentrosincronico',
            name='titulo',
        ),
        migrations.AddField(
            model_name='encuentrosincronico',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
