# Generated by Django 5.1.3 on 2024-11-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_remove_encuentrosincronico_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentrosincronico',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
